name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - run: |
        chmod +x ./gradlew
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        ./gradlew :module:assembleRelease
        cp -r module/files/* out/module_release/
    - uses: actions/upload-artifact@v4
      with:
        name: better-il2cppdumper
        path: out/module_release/
